name: Landing Page CI & Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - "landing_page/**"
  pull_request:
    paths:
      - "landing_page/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: landing_page
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build

      # Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: landing-page-build
          path: landing_page/dist  # This should match your Vite build output

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: landing-page-build
          path: dist  # This will download to the root dist folder

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist  # This should point to the downloaded artifact

  preview:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: landing-page-build
          path: dist

      # Deploy PR preview using Surge
      - name: Install Surge
        run: npm install -g surge

      - name: Deploy PR Preview
        id: surge
        run: |
          PREVIEW_URL=${{ github.head_ref }}-preview-${{ github.run_id }}.surge.sh
          surge ./dist $PREVIEW_URL
          echo "url=https://$PREVIEW_URL" >> $GITHUB_OUTPUT
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

      # Comment the PR with preview URL
      - name: Comment PR with preview link
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚀 Preview for this PR is available here:  
            👉 [${{ steps.surge.outputs.url }}](${{ steps.surge.outputs.url }})
